Build ciris-enumeratum with Scala 3
This PR cross builds ciris-enumeratum with Scala 3:

* Scala 3 has been added to the enumeratum's `crossScalaVersions`
* The `TypeNameRuntimePlatform` has been splitted for Scala 2 and
  Scala 3. The Scala 3 implementation has been copied from the refined
  module.
* `-Yretain-trees` was added to the Scala 3 `scalacOptions` to fix test
  compilation errors:
  ```
  sbt:ciris> enumeratumJVM/test
  [info] compiling 2 Scala sources to modules/enumeratum/jvm/target/scala-3.2.2/test-classes ...
  [error] -- Error: modules/enumeratum/shared/src/test/scala/enumeratum/values/CirisValueEnumSpec.scala:216:17
  [error] 216 |    val values = findValues
  [error]     |                 ^^^^^^^^^^
  [error]     |                 Option -Yretain-trees must be set in scalacOptions.
  [error]     |                 In SBT settings:
  [error]     |
  [error]     |                   scalacOptions += "-Yretain-trees"
  ```
  It is expected that this must be set:
  https://github.com/lloydmeta/enumeratum/blob/1facfdddd9498411ac8eb270cd8089d4b4f4cab0/README.md?plain=1#L28